title: Chaithanya Kumar
email: chaithanyakumar.ds@gmail.com
description: Blogs on data science, machine learning, visualization, MLOps
url: https://sck22.github.io # the base hostname & protocol for your site
baseurl: "/sck-blogs" # the subpath of your site, e.g. /blog
github_username: sck22

blog_name: SCK's Blog  # your blog must have a name for it to show up in the nav bar
blog_description: a simple whitespace theme for academics
permalink: /blog/:year/:title/

show_excerpts: true
# code highlighter theme
highlight_theme_light: github   # https://github.com/jwarby/jekyll-pygments-themes
highlight_theme_dark: native    # https://github.com/jwarby/jekyll-pygments-themes
# repo color theme
repo_theme_light: default       # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_theme_dark: dark           # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
rss_icon: true
theme: minima
plugins:
  - jekyll-feed

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 5